name: Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Test and build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: cargo test
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md"
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@master
        with:
          name: Binaries
          path: binaries
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "binaries/*"
